<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.11.11.3 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id$
 * Date: Sun, 30 Jun 2013 03:28:53 GMT
 */

/* Servers configuration */
$i = 0;

/* Server cs-server.usc.edu (config:root) [1] */
$i++;
$cfg['Servers'][$i]['host'] = 'cs-server.usc.edu';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['port'] = '7787';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'richard';

$cfg['Servers'][$i]['AllowDeny']['order'] = '';

$cfg['Servers'][$i]['AllowDeny']['rules'] = array();



/* End of servers configuration */

?>
